CREATE TABLE IF NOT EXISTS event
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_reference_id VARCHAR(255) NOT NULL,
    name               VARCHAR(255) NOT NULL,
    start_time         TIMESTAMP    NOT NULL,
    end_time           TIMESTAMP    NOT NULL,
    CONSTRAINT fk_event_venue FOREIGN KEY (venue_reference_id)
        REFERENCES venue (reference_id)
);

CREATE INDEX idx_event_venue ON event (venue_reference_id);